name: Deploy static content to Pages
on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Prepare website
        run: |
          mkdir -p _site
          
          # html/ becomes /
          cp -r html/. _site/
          
          # 2. Vulnerabilities/5. Demo/ becomes /demo/
          mkdir -p _site/demo
          cp -r "2. Vulnerabilities/5. Demo/." _site/demo/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
